name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rails_version: [7.1.5, 7.2.2]
        ruby: [3.3]
        additional_engine_cart_rails_options: [""]
        include:
          - ruby: 3.2
            rails_version: 7.1.5
          - ruby: 3.1
            rails_version: 7.0.8.4
          - ruby: 3.3
            rails_version: 8.0.0
            additional_engine_cart_rails_options: --css=bootstrap
    env:
      RAILS_VERSION: ${{ matrix.rails_version }}
      ENGINE_CART_RAILS_OPTIONS: "--skip-git --skip-listen --skip-spring --skip-keeps --skip-kamal --skip-solid --skip-coffee --skip-test ${{ matrix.additional_engine_cart_rails_options }}"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies with Rails ${{ matrix.rails_version }}
        run: bundle install
      - name: Run tests
        run: bundle exec rake
